### ISSUE TITLE
Add support for views exposed filter "Content: Has taxonomy term" autocomplete widget

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/entityreference#2]
No matter what I do, the exposed filter always looks like a select list drop down.

![group-filter](https://cloud.githubusercontent.com/assets/13283396/13193994/66b4bf8a-d740-11e5-9e3f-c17eacb7cb1c.PNG)

**Comment by signalpoint** [comment]
@mkinnan Well this is modeled after Drupal's UI. AFAIK, there is no autocomplete exposed filter for entity reference field (maybe there is with the Views Better Exposed Filters). Do you have an autocomplete entity reference exposed filter somewhere on your Drupal site. How did you get that?

**Comment by mkinnan** [comment]
Since my referenced entity is a taxonomy term, on my Drupal site I added the filter **Content: Has taxonomy term**. I tried this for my drupalgap view and it does that same thing as presented in the image above even the filter widget setting is set as _autocomplete_.

In console log, I see the following error when I use the **Content: Has taxonomy term** filter

`list_views_exposed_filter - TypeError: Cannot set property 'All' of null`

**Comment by signalpoint** [comment]
@mkinnan Turns out this was an issue in DG core, it is now resolved.
