### ISSUE TITLE
Entity reference field is not saved

### ISSUE THREAD

**Issue by luxio** [signalpoint/entityreference#5]
When creating a node with an entity reference field (field_reldated_task), the entity reference field ist not saved. 

I think the post request looks good:

```
{"nid":"",
"title":"DiaryPad User on Simple Group Discussion",
"type":"post",
"language":"und",
"og_group_ref":{"und":["1083"]},
"body":{"und":[{"value":"test"}]},
"field_reldated_task":{"und":[{"target_id":"... (1950)"}]}
,"field_media":{"und":[{"fid":""}]}}
```

Any ideas? Do I need a patch for the service module?

**Comment by signalpoint** [comment]
@luxio The `"field_reldated_task":{"und":[{"target_id":"... (1950)"}]}` format only works for the autocomplete fields. The `... (#)` is meant to simulate what is normally input into those fields on the Drupal UI.

Otherwise, I think the format needs to be like this: `"field_reldated_task":{"und":[{"target_id":"1950"}]}` if you're using any of the other widget on the `Manage fields` page in Drupal for your bundles.

**Comment by luxio** [comment]
@signalpoint The postrequest was generated from a default create node form (not manually). The `field_reldated_task` was selected with the autocomplete widget in DG.

**Comment by signalpoint** [comment]
@luxio Are there any watchdog notices being thrown? Usually a failure to save an entity reference means the target doesn't exist, it's an invalid id for the bundle, or the user doesn't have access to the entity (usually via some kind of node access, og, etc).

**Comment by luxio** [comment]
@signalpoint no errors,  only a message the the node was created.

**Comment by luxio** [comment]
Took me quite some time to figure it out.

The reason was, that I was using Entity reference prepopulate to fill out this field, and the form field was hidden, if no value was provided in the URL. The result was hat `drupal_form_submit()`could not save the field.

**Comment by signalpoint** [comment]
@luxio To confirm, entity reference prepopulate does interfere with the Services POST? The way around it is to include the prepopulate url query string in the POST url? e.g. `?q=drupalgap/node.json&field_reldated_task=123`

**Comment by luxio** [comment]
@signalpoint That could work. 

I just set **Fallback behaviour** from **Hide field** to **Do noting** in the field settings:

![screen shot 2016-09-21 at 16 18 09](https://cloud.githubusercontent.com/assets/1497217/18714733/0c99d5b4-8017-11e6-9568-13a2d2556498.png)
