### ISSUE TITLE
What is the Simple selection mode?

### ISSUE THREAD

**Issue by luxio** [signalpoint/entityreference#6]
The DG docs says for  [Entity References](http://docs.drupalgap.org/7/Entities/Entity_Reference):

> We can either use the Simple selection mode on our Entity reference field's widget to have DrupalGap automatically handle the field, 

What is the **Simple selection mode**?  A **Select List** Widget?

**Comment by signalpoint** [comment]
@luxio That is under the field instance settings, see attached screenshot for reference: 
![screenshot from 2016-09-20 09 55 40](https://cloud.githubusercontent.com/assets/671140/18673083/6e177cec-7f18-11e6-8bde-8f2087f86fc7.png)

**Comment by luxio** [comment]
Which widget type should I use for the Simple Mode?

**Comment by signalpoint** [comment]
@luxio I think the autocomplete widget(s) work best. The select list, radio, and checkboxes shold work if the number of entities is relatively small.

**Comment by luxio** [comment]
@signalpoint If use the autocomplete widget and the simple mode, I get:

```
_theme_autocomplete - ReferenceError: entityreference_get_target_bundles is not defined
```

**Comment by luxio** [comment]
@signalpoint Sorry, I did not had the current version of the DG entityreference module.
